SELECT
    C.NUM_DOSS,
    C.JOUR,
    C.DAT_ADMINI,
    C.COD_CATEG_PROTO,
    C.COD_TYP_PROTO,
    C.NUM_PDT,
    C.NOM_PDT,
    C.COD_VOIE,
    C.UF_REAL,
    C.LIB_UF_REAL,
    C.DOSE_TOT,
    C.NOM_PROTO,
    C.NOM_MODA,
    C.CE_ETAT_CHIMIO
FROM
    DWH.CHIMIOTHERAPIE C
