WITH lignes_base AS (
  SELECT
    pa.NOOBSPAT as noobspat,
    pr.NUMCYCLE AS cycle_number,
    TO_DATE(lp.DATEDEBADMR, 'YYYYMMDD') AS start_date,
    TO_DATE(lp.DATEFINADMR, 'YYYYMMDD') AS end_date
  FROM CHIMIODATA.INCLUSIO inc
  JOIN CHIMIODATA.PATIENT pa ON pa.PACLEUNIK = inc.PACLEUNIK
  LEFT JOIN CHIMIODATA.PRESCRIP pr ON pr.I0CLEUNIK = inc.I0CLEUNIK
  LEFT JOIN CHIMIODATA.LIGNEPRE lp ON lp.P0CLEUNIK = pr.P0CLEUNIK
  WHERE
    pa.NOOBSPAT IS NOT NULL
    AND pr.NUMCYCLE IS NOT NULL
    AND lp.DATEDEBADMR IS NOT NULL
    AND lp.DATEFINADMR IS NOT NULL
    AND LENGTH(TRIM(lp.DATEDEBADMR)) = 8
    AND LENGTH(TRIM(lp.DATEFINADMR)) = 8
)

SELECT *
FROM lignes_base
ORDER BY noobspat, cycle_number, start_date
