SELECT
    C.CP_NUMDOSS AS NUM_DOSS,
    C.CP_NUM_J AS JOUR,
    C.CP_DATE_ADM AS DAT_ADMINI,
    NULL AS COD_CATEG_PROTO,
    C.CP_LIB_TYPE_PDT AS COD_TYP_PROTO,
    C.CP_CODE_PDT AS NUM_PDT,
    C.CP_LIB_UCD AS NOM_PDT,
    C.CP_CODE_VOIE_ADM AS COD_VOIE,
    C.CP_CODE_SERV AS UF_REAL,
    C.CP_LIB_SERV AS LIB_UF_REAL,
    COALESCE(C.CP_QTE_PDT_UTILISEE, C.CP_DOSE_PREVUE) AS DOSE_TOT,
    P.CP_NOM AS NOM_PROTO,
    C.CP_LIB_TYPE_PDT AS NOM_MODA,
    COALESCE(C.CP_STATUT, C.CP_ETAT) AS CE_ETAT_CHIMIO,
    C.CP_CODE_UCD AS CODE_UCD,
    C.CP_CODE_DCI AS CODE_DCI,
    C.CP_LIB_DCI AS LIB_DCI,
    P.CP_NOM AS NOM_PROTOCOLE
FROM
    DMI_ICR.CHIMIO_PRESCRIPTION C
    LEFT JOIN DMI_ICR.CHIMIO_INCLUSION_CE I
        ON C.CP_NUM_INCLUSION_CE = I.CIE_KEY_INCLUS
    LEFT JOIN DMI_ICR.CHIMIO_PROTO P
        ON I.CIE_CODE_PROTO = P.CP_CODE_PROTO
WHERE 
    C.CP_LIB_ETAPE_PRESC = 'ADMINISTRE'
