SELECT
    ori.I_LABEL,
    ori.I_PATIENT_KEY,
    ori.I_PLANNED_START,
    ori.I_PLANNED_END,
    ori.I_KEY,
    pat.P_CODE,
    fi.IN_CODE AS IN_CODE
FROM C3.OR_INTERVENTIONS ori
INNER JOIN C3.PATIENTS pat
    ON ori.I_PATIENT_KEY = pat.P_KEY
LEFT JOIN C3.OR_INTERVENTION_BILLING_FR ibfr
    ON ibfr.IBFR_INTERVENTION_KEY = ori.I_KEY
LEFT JOIN C3.OR_INTERVENTION_BILL_FR_CODES ibfrc
    ON ibfrc.IBFRC_BILLING_KEY = ibfr.IBFR_KEY
LEFT JOIN C3.F_INT fi
    ON fi.IN_KEY = ibfrc.IBFRC_BILLINGCODE_KEY
WHERE pat.P_CODE IS NOT NULL
