SELECT
    pa.NOOBSPAT,
    pr.NUMCYCLE AS cycle_number,
    TO_DATE(lp.DATEDEBADMR, 'YYYYMMDD') AS start_date,
    TO_DATE(lp.DATEFINADMR, 'YYYYMMDD') AS end_date,
    prot.NOMPROT AS protocol_name,
    prot.TYPEPROT AS protocol_type,
    prod.CODEPDT,
    prod.NOMPDT AS drug_name,
    lp.CODEVOIE AS code_voie,
    lp.UNITE,
    lp.DOSEADM AS dose_adm,
    CASE
        WHEN prod.NOMPDT IS NULL
          OR LOWER(TRIM(prod.NOMPDT)) IN ('sans', '(sans)')
          OR prod.NOMPDT LIKE '!! %'
        THEN 0 ELSE 1
    END AS is_real_drug
FROM CHIMIODATA.PATIENT pa
JOIN CHIMIODATA.INCLUSIO inc ON inc.PACLEUNIK = pa.PACLEUNIK
JOIN CHIMIODATA.PRESCRIP pr ON pr.I0CLEUNIK = inc.I0CLEUNIK
JOIN CHIMIODATA.LIGNEPRE lp ON lp.P0CLEUNIK = pr.P0CLEUNIK
LEFT JOIN CHIMIODATA.PRODUIT prod ON prod.CODEPDT = lp.CODEPDT
LEFT JOIN CHIMIODATA.PROTOCOL prot ON prot.PRCLEUNIK = inc.PRCLEUNIK
WHERE
    pr.NUMCYCLE IS NOT NULL
    AND lp.DATEDEBADMR IS NOT NULL
    AND lp.DATEFINADMR IS NOT NULL
    AND LENGTH(TRIM(lp.DATEDEBADMR)) = 8
    AND LENGTH(TRIM(lp.DATEFINADMR)) = 8

ORDER BY pa.NOOBSPAT, pr.NUMCYCLE, start_date
