SELECT
    CAI_NUMDOSS,
    CAI_DATE_REAL,
    CAI_CODE_CCAM,
    CAI_THEME,
    CAI_CODE_CCAM_FACT,
    CAI_DATE_SUPPRESSION
FROM DMI_ICR.COLLECTEUR_ACTE_ICR
WHERE CAI_DATE_SUPPRESSION IS NULL
  AND CAI_DATE_REAL > TIMESTAMP '2023-01-01 00:00:00'
