name: ETL Oncopole Deploy

on:
  push:
    branches: [ version_1 ]

jobs:
  deploy:
    name: Deploy to Airflow Server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Déployer dans ~/airflow/dags/osiris_oncopole (sans écraser le reste)
        run: |
          set -e

          TARGET="$HOME/airflow/dags/osiris_oncopole"

          echo "Cleaning project folder: $TARGET"
          rm -rf "$TARGET"
          mkdir -p "$TARGET"

          echo "Copying tracked files to $TARGET"
          git ls-files | while read file; do
            mkdir -p "$TARGET/$(dirname "$file")"
            cp -r "$file" "$TARGET/$file"
          done

          echo "Deployment finished"

      - name: Redémarrer Airflow
        run: |
          sudo systemctl restart airflow-webserver.service
          sudo systemctl restart airflow-scheduler.service
