name: ETL Oncopole Deploy

on:
  push:
    branches: [ version_1 ]

jobs:
  deploy:
    name: Deploy to Airflow Server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Nettoyer le dossier Airflow DAGs
        run: |
          rm -rf ~/airflow/dags/*

      - name: Copier les fichiers suivis par Git vers Airflow
        run: |
          git ls-files -z | xargs -0 -I{} cp -r {} ~/airflow/dags/

      - name: Redémarrer Airflow
        run: |
          sudo systemctl restart airflow-webserver.service
          sudo systemctl restart airflow-scheduler.service

